#######################################################################################
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Energy Data Analysis with Python
author: Reto Marek
copyright: "2026"
logo: logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "auto"
  timeout: 180
  allow_errors: false

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

#######################################################################################
# HTML-specific settings
html:
  favicon: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: true
  home_page_in_navbar: true
  extra_footer: ""

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: false

#######################################################################################
# Repository settings
repository:
  url: https://github.com/retomarek/edap
  path_to_book: edap
  branch: main

#######################################################################################
# Sphinx settings
sphinx:
  recursive_update: true
  extra_extensions:
    - sphinx_togglebutton
    - sphinx_copybutton
    - sphinx_design
  config:
    togglebutton_hint: "Show"
    togglebutton_hint_hide: "Hide"
    copybutton_prompt_text: ">>> |\\$ |In \\[\\d*\\]: |\\.\\.\\.: "
    copybutton_prompt_is_regexp: true
    html_show_copyright: true
    html_js_files:
      - custom.js
    html_css_files:
      - custom.css
    html_theme_options:
      use_download_button: false

#######################################################################################
# BibTeX settings
bibtex_bibfiles:
  - references.bib
