#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Energy Data Analysis with Python  # The title of the book. Will be placed in the left navbar.
author                      : Reto Marek  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
#logo                        : logo.png  # A path to the book logo

#######################################################################################
# Launch button settings
launch_buttons:
  binderhub_url             : false  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : false
  
repository:
  url                       : https://github.com/retomarek/edap/  # The URL to your book's repository
  path_to_book              : "/edap"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links